development:
  # CHANGE THIS: from 'async' to 'redis'
  adapter: redis
  # Use the standard local Redis URL
  url: redis://localhost:6379/1
  channel_prefix: action_cable_demo_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: action_cable_demo_production
